// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtcsemfhmemziioqtjfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0Y3NlbWZobWVtemlpb3F0amZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NzE5MDcsImV4cCI6MjA2MTI0NzkwN30.tsRpYkEuYI5lY8dDzzErNh8qLTcR9RSTmjVXkpB5EJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);